"""
Database initialization script
Run this to create all database tables
"""
import sys
import os

# Add backend directory to path
backend_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'backend'))
sys.path.insert(0, backend_path)

from app.database import init_db, engine
from app.models import Base, RequiredDocument, DocumentType
from sqlalchemy.orm import Session
from loguru import logger


def seed_required_documents():
    """Seed the database with required documents for Iceland tourist visa
    
    NEW SYSTEM:
    - Only 3 MANDATORY documents: Passport, NID Bangla, Bank Solvency
    - All other documents are OPTIONAL - upload if available, generate if not
    - System can analyze ALL 16 document types
    """
    
    with Session(engine) as session:
        try:
            # Check if data already exists
            existing = session.query(RequiredDocument).first()
            if existing:
                logger.info("Required documents already seeded")
                return
            
            # ===== MANDATORY DOCUMENTS (3 - MUST upload) =====
            mandatory_documents = [
                ('passport_copy', 'Valid passport copy - REQUIRED', False, True),
                ('nid_bangla', 'National ID card (Bangla) - REQUIRED', False, True),
                ('bank_solvency', 'Bank solvency certificate - REQUIRED', False, True),
            ]
            
            # ===== OPTIONAL USER DOCUMENTS (5 - upload if available) =====
            optional_user_documents = [
                ('visa_history', 'Previous visa history from passport (Optional - helps with travel history)', False, False),
                ('tin_certificate', 'Tax Identification Number certificate (Optional)', False, False),
                ('income_tax_3years', 'Income tax returns for last 3 years (Optional - helps with financial statement)', False, False),
                ('hotel_booking', 'Hotel booking confirmation (Optional - helps with itinerary)', False, False),
                ('air_ticket', 'Air ticket booking (Optional - helps with itinerary)', False, False),
            ]
            
            # ===== GENERATED DOCUMENTS (8 - Always generated by AI) =====
            generated_documents = [
                ('asset_valuation', 'Asset valuation certificate - Generated by AI from questionnaire and uploaded docs', True, False),
                ('nid_english', 'National ID English translation - Generated from Bangla NID', True, False),
                ('visiting_card', 'Professional visiting card - Generated from applicant information', True, False),
                ('cover_letter', 'Visa application cover letter - MOST IMPORTANT - Generated from ALL data', True, False),
                ('travel_itinerary', 'Detailed travel itinerary - Generated from bookings or questionnaire', True, False),
                ('travel_history', 'Travel history summary - Generated from visa stamps or questionnaire', True, False),
                ('home_tie_statement', 'Home tie statement letter - Generated showing connections to Bangladesh', True, False),
                ('financial_statement', 'Financial statement summary - Generated from bank and tax documents', True, False),
            ]
            
            # Add mandatory documents
            for doc_type, description, can_generate, is_mandatory in mandatory_documents:
                doc = RequiredDocument(
                    country="Iceland",
                    visa_type="Tourist",
                    document_type=DocumentType[doc_type.upper()],
                    is_mandatory=is_mandatory,  # True for these 3
                    description=description,
                    can_be_generated=can_generate
                )
                session.add(doc)
            
            # Add optional user documents
            for doc_type, description, can_generate, is_mandatory in optional_user_documents:
                doc = RequiredDocument(
                    country="Iceland",
                    visa_type="Tourist",
                    document_type=DocumentType[doc_type.upper()],
                    is_mandatory=is_mandatory,  # False for optional
                    description=description,
                    can_be_generated=can_generate
                )
                session.add(doc)
            
            # Add generated documents (not mandatory to upload, will be generated)
            for doc_type, description, can_generate, is_mandatory in generated_documents:
                doc = RequiredDocument(
                    country="Iceland",
                    visa_type="Tourist",
                    document_type=DocumentType[doc_type.upper()],
                    is_mandatory=is_mandatory,  # False - will be generated
                    description=description,
                    can_be_generated=can_generate
                )
                session.add(doc)
            
            session.commit()
            logger.info("Successfully seeded required documents")
            
        except Exception as e:
            logger.error(f"Error seeding database: {str(e)}")
            session.rollback()
            raise


if __name__ == "__main__":
    logger.info("Initializing database...")
    
    # Create all tables
    init_db()
    
    # Seed required documents
    seed_required_documents()
    
    logger.info("Database initialization completed successfully!")
